platform :ios, '8.0'

use_frameworks!

pod 'Alamofire', '3.3.0'
pod 'AlamofireObjectMapper', '3.0.0'
pod 'AlamofireImage', '2.4.0'
pod 'XCGLogger', '3.3'
pod 'Swinject', '1.1.1' # TODO: upgrade for Xcode 7.3!
pod 'KeychainSwift', '3.0.13'
pod 'OrderedSet', :git => 'https://github.com/Weebly/OrderedSet.git', :commit => '39ac853' # TODO: upgrade after new release
pod 'SwiftyTimer', '1.4.0'
pod 'SwiftDate', '3.0.8'
pod 'RealmSwift', '0.100.0' # TODO: upgrade for Xcode 7.3!
pod 'TaskQueue', '0.9.10'
pod 'AsyncSwift', '1.7.2'
pod 'ReachabilitySwift', '2.3.3'

target :PonyTests, :exclusive => true do
  pod 'Quick', '0.9.2'
  pod 'Nimble', '4.0.1'
end