platform :ios, '8.0'

use_frameworks!

pod 'Alamofire', '3.3.0'
pod 'AlamofireObjectMapper', '3.0.0'
pod 'XCGLogger', '3.3'
pod 'Swinject', '1.1.1' # TODO: upgrade for Xcode 7.3!
pod 'SwiftyJSON', '2.3.2' # TODO: upgrade for Xcode 7.3!
pod 'KeychainSwift', '3.0.13'
pod 'OrderedSet', :git => 'https://github.com/Weebly/OrderedSet.git', :commit => '39ac853' # TODO: upgrade after new release

target :PonyTests, :exclusive => true do
  pod 'Quick', '0.9.2'
  pod 'Nimble', '4.0.1'
end