source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'Pony' do

	pod 'Alamofire', '3.3.0'
	pod 'AlamofireObjectMapper', '3.0.0'
	pod 'AlamofireImage', '2.4.0'
	pod 'XCGLogger', '3.3'
	pod 'Swinject', '1.1.1'
	pod 'KeychainSwift', '3.0.13'
	pod 'OrderedSet', :git => 'https://github.com/Weebly/OrderedSet.git', :commit => '39ac853' # TODO: upgrade after new release
	pod 'SwiftyTimer', '1.4.0'
	pod 'SwiftDate', '3.0.8'
	pod 'RealmSwift', '0.101.0'
	pod 'TaskQueue', '0.9.10'
	pod 'AsyncSwift', '1.7.2'
	pod 'ReachabilitySwift', '2.3.3'
	pod 'Localize-Swift', '1.1.2'
	pod 'STRegex', '0.3.1'
	pod 'HanekeSwift', '0.10.1'
	pod 'MRProgress', '0.8.3'

	target 'PonyTests' do
		inherit! :search_paths

		pod 'Quick', '0.9.2'
		pod 'Nimble', '4.0.1'
	end
end
